# Scroll down to get the QUIZ 3 solutions.

# QUIZ 1: Solution

# Load Data

In [1]:
import pandas as pd

# Replace 'your_excel_file.xlsx' with the path to your Excel file
excel_file = 'sales data.xlsx'

# Load Excel data into a pandas DataFrame
df = pd.read_excel(excel_file)

# Now, you can work with the data in the 'df' DataFrame
# For example, you can print the first few rows of the DataFrame
df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,98320.37,77722.25,8/23/2020,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466
1,France,46296.26,40319.41,5/15/2020,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
2,Portugal,140337.34,115708.14,2020-04-09 00:00:00,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141
3,France,203604.46,175344.16,6/26/2019,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106
4,UK,63979.04,56032.84,10/22/2019,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546

# Missing Values

In [2]:
# Check for missing values in the entire DataFrame
missing_values = df.isnull().sum()

# To check for missing values in a specific column, you can use:
# missing_values = df['column_name'].isnull().sum()

# Print the columns with missing values and their respective counts
print("Missing Values:")
print(missing_values[missing_values > 0])

Missing Values:
order_value_EUR    5
device_type        5
dtype: int64

In [3]:
from sklearn.impute import SimpleImputer

target_column = 'order_value_EUR'

# Create a SimpleImputer instance to impute missing values with a strategy (e.g., 'mean', 'median', 'most_frequent')
# Other strategies include 'constant' to replace missing values with a constant value
imputer = SimpleImputer(strategy='median')

# Fit the imputer on the selected column and transform it to impute missing values
df[target_column] = imputer.fit_transform(df[[target_column]])

In [4]:
df.isnull().sum()

country            0
order_value_EUR    0
cost               0
date               0
category           0
customer_name      0
sales_manager      0
sales_rep          0
device_type        5
order_id           0
dtype: int64

In [5]:
df.device_type

0       Tablet
1       Tablet
2           PC
3       Mobile
4           PC
         ...
996         PC
997     Tablet
998     Tablet
999         PC
1000        PC
Name: device_type, Length: 1001, dtype: object

In [6]:
target_column = 'device_type'

# Create a SimpleImputer instance to impute missing values with a strategy (e.g., 'mean', 'median', 'most_frequent')
# Other strategies include 'constant' to replace missing values with a constant value
imputer = SimpleImputer(strategy='most_frequent')

# Fit the imputer on the selected column and transform it to impute missing values
df[target_column] = imputer.fit_transform(df[[target_column]])

In [7]:
df.isnull().sum()

country            0
order_value_EUR    0
cost               0
date               0
category           0
customer_name      0
sales_manager      0
sales_rep          0
device_type        0
order_id           0
dtype: int64

# Inconsistent Values

In [8]:
df.dtypes

country             object
order_value_EUR    float64
cost                object
date                object
category            object
customer_name       object
sales_manager       object
sales_rep           object
device_type         object
order_id            object
dtype: object

In [9]:
# Sample variable containing mixed data
mixed_data = df['cost']

# Create an empty list to store non-numeric values
non_numeric_values = []

# Iterate through the elements in the variable
for value in mixed_data:
    if isinstance(value, str) and not value.isnumeric():
        non_numeric_values.append(value)

# Print the non-numeric values
print("Non-Numeric Values:")
print(non_numeric_values)

Non-Numeric Values:
['XXX']

In [10]:
mask = (df['cost'] == 'XXX')

# Remove rows that match the mask
df = df[~mask]

# Data Types

In [11]:
df['cost'] = df['cost'].astype(float)

# Print the DataFrame with the corrected data type
print(df.dtypes)

country             object
order_value_EUR    float64
cost               float64
date                object
category            object
customer_name       object
sales_manager       object
sales_rep           object
device_type         object
order_id            object
dtype: object

In [12]:
df['date'] = df['date'].astype('datetime64')

In [13]:
df.dtypes

country                    object
order_value_EUR           float64
cost                      float64
date               datetime64[ns]
category                   object
customer_name              object
sales_manager              object
sales_rep                  object
device_type                object
order_id                   object
dtype: object

In [14]:
df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,98320.37,77722.25,2020-08-23,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466
1,France,46296.26,40319.41,2020-05-15,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
2,Portugal,140337.34,115708.14,2020-04-09,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141
3,France,203604.46,175344.16,2019-06-26,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106
4,UK,63979.04,56032.84,2019-10-22,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546

# Duplicates Data

In [15]:
# Identify duplicate rows based on all columns
duplicates = df[df.duplicated()]

# Print duplicate rows
print("Duplicate Rows:")
duplicates

Duplicate Rows:

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
23,UK,63979.04,56032.84,2019-10-22,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546

In [16]:
# Remove duplicate rows, keeping the first occurrence
df_no_duplicates = df.drop_duplicates()

# Print the DataFrame without duplicates
print("DataFrame without Duplicates:")
df_no_duplicates

DataFrame without Duplicates:

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,98320.37,77722.25,2020-08-23,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466
1,France,46296.26,40319.41,2020-05-15,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
2,Portugal,140337.34,115708.14,2020-04-09,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141
3,France,203604.46,175344.16,2019-06-26,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106
4,UK,63979.04,56032.84,2019-10-22,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546
...,...,...,...,...,...,...,...,...,...,...
996,France,69126.50,55902.60,2019-08-12,Electronics,"Farrell, Swaniawski and Crist",Othello Bowes,Avrit Chanders,PC,07-3201531
997,France,140943.88,120633.87,2020-05-28,Appliances,Armstrong-Little,Othello Bowes,Avrit Chanders,Tablet,77-0650807
998,France,124784.67,106853.11,2020-05-22,Electronics,"Swaniawski, Runolfsson and Green",Othello Bowes,Ora Grennan,Tablet,44-2757396
999,Germany,61968.26,50690.04,2020-12-27,Electronics,Romaguera-Dietrich,Rickard Doogood,Casie MacBain,PC,22-7259031
1000,Netherlands,172453.10,145688.38,2020-06-24,Outdoors,Kirlin and Sons,Denice Amberg,Nero Harbisher,PC,60-6986682

In [17]:
cleaned_data = df_no_duplicates

In [18]:
cleaned_data.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,98320.37,77722.25,2020-08-23,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466
1,France,46296.26,40319.41,2020-05-15,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
2,Portugal,140337.34,115708.14,2020-04-09,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141
3,France,203604.46,175344.16,2019-06-26,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106
4,UK,63979.04,56032.84,2019-10-22,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546

# QUIZ 2: Solution

# Data Sorting

In [19]:
df_sorted = df.sort_values(by='cost', ascending=True)

In [20]:
df_sorted

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
422,Sweden,15100.570,12113.68,2019-02-20,Games,"Murray, Reichel and Nolan",Maxie Marrow,Tarrah Castelletti,PC,89-2424262
275,France,16388.900,13430.70,2020-03-15,Electronics,West-Cummings,Othello Bowes,Crysta Halls,PC,30-9690927
17,Sweden,15817.050,13743.44,2019-10-03,Clothing,Kihn Inc,Maxie Marrow,Anita Woakes,PC,26-9787272
971,Netherlands,105357.645,14102.75,2020-07-02,Clothing,Johns and Sons,Denice Amberg,Nero Harbisher,PC,38-5910704
138,Sweden,17524.020,14122.61,2020-12-02,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,02-3364199
...,...,...,...,...,...,...,...,...,...,...
766,Sweden,325331.990,264592.51,2019-12-23,Games,Altenwerth-Konopelski,Maxie Marrow,Caro Morfield,Mobile,57-4142025
242,Luxembourg,312928.720,270401.71,2019-12-12,Beauty,Altenwerth-Konopelski,Ilsa Kob,Jocelyn Laurentino,Tablet,98-5257166
413,Netherlands,353925.060,287528.72,2020-04-12,Clothing,Corwin and Sons,Denice Amberg,Nero Harbisher,PC,36-2694099
84,Ireland,361182.870,288368.40,2019-02-12,Books,Smith Group,Glenine Suttaby,Bunnie Tonbridge,PC,44-1953194
986,UK,383996.760,304701.43,2019-12-19,Other,Johns and Sons,Jessamine Apark,Winny Agnolo,PC,42-7823733

# Conditional Filtering

In [21]:
France_df = df[df['country'] == 'France']
France_df

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
1,France,46296.26,40319.41,2020-05-15,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
3,France,203604.46,175344.16,2019-06-26,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106
7,France,96795.99,81395.75,2019-06-21,Appliances,Connelly-Mohr,Othello Bowes,Avrit Chanders,PC,32-3124563
16,France,65193.88,53113.45,2019-04-10,Beauty,Friesen and Sons,Othello Bowes,Maighdiln Upcraft,PC,74-1131921
18,France,54079.04,45031.62,2020-05-29,Games,"Lueilwitz, Kerluke and Lesch",Othello Bowes,Avrit Chanders,PC,15-6838362
...,...,...,...,...,...,...,...,...,...,...
993,France,167072.72,135044.88,2019-10-21,Clothing,O'Connell-Mitchell,Othello Bowes,Ora Grennan,PC,37-6449638
994,France,157932.84,134148.15,2020-01-31,Games,"Schowalter, Lesch and Beahan",Othello Bowes,Amelina Piscopiello,PC,30-2982340
996,France,69126.50,55902.60,2019-08-12,Electronics,"Farrell, Swaniawski and Crist",Othello Bowes,Avrit Chanders,PC,07-3201531
997,France,140943.88,120633.87,2020-05-28,Appliances,Armstrong-Little,Othello Bowes,Avrit Chanders,Tablet,77-0650807
998,France,124784.67,106853.11,2020-05-22,Electronics,"Swaniawski, Runolfsson and Green",Othello Bowes,Ora Grennan,Tablet,44-2757396

In [22]:
France_Games_df = df[(df['country'] == 'France') & (df['category'] == 'Games')]
France_Games_df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
1,France,46296.26,40319.41,2020-05-15,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
18,France,54079.04,45031.62,2020-05-29,Games,"Lueilwitz, Kerluke and Lesch",Othello Bowes,Avrit Chanders,PC,15-6838362
50,France,149500.61,125401.11,2020-07-24,Games,McGlynn-Bergstrom,Othello Bowes,Crysta Halls,PC,60-8646184
104,France,146325.53,118333.46,2020-09-08,Games,Stehr-Bogan,Othello Bowes,Crysta Halls,PC,95-8015610
137,France,133754.65,106147.69,2020-09-18,Games,Armstrong-Little,Othello Bowes,Ora Grennan,PC,52-3150154

In [23]:
Not_France_df = df[df['country'] != 'France']
Not_France_df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,98320.37,77722.25,2020-08-23,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466
2,Portugal,140337.34,115708.14,2020-04-09,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141
4,UK,63979.04,56032.84,2019-10-22,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546
5,Italy,127075.41,110924.13,2019-09-24,Clothing,Labadie and Sons,Piggy Roscrigg,Joshua Prevost,PC,57-6602854
6,Sweden,69681.43,55529.13,2020-01-25,Clothing,Romaguera-Dietrich,Maxie Marrow,Alyosha Meah,PC,78-3301264

# Data Merging

In [24]:
# Replace 'your_excel_file.xlsx' with the path to your Excel file
excel_file = 'Extra Variable.xlsx'

# Load Excel data into a pandas DataFrame
extra_vars = pd.read_excel(excel_file)

# Now, you can work with the data in the 'df' DataFrame
# For example, you can print the first few rows of the DataFrame
extra_vars.head()

     order_id  refund
0  70-0511466   43621
1  77-3489084   13385
2  65-8218141   69535
3  29-5478106   90064
4  57-6602854   61736

In [25]:
merged_df = cleaned_data.merge(extra_vars, on='order_id')
merged_df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id,refund
0,Sweden,98320.37,77722.25,2020-08-23,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466,43621
1,France,46296.26,40319.41,2020-05-15,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084,13385
2,Portugal,140337.34,115708.14,2020-04-09,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141,69535
3,France,203604.46,175344.16,2019-06-26,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106,90064
4,UK,63979.04,56032.84,2019-10-22,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546,24176

# Data Concatenating

In [26]:
# Replace 'your_excel_file.xlsx' with the path to your Excel file
excel_file = 'Extra Data.xlsx'

# Load Excel data into a pandas DataFrame
extra_data = pd.read_excel(excel_file)

# Now, you can work with the data in the 'df' DataFrame
# For example, you can print the first few rows of the DataFrame
extra_data.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id,refund
0,Sweden,17524.02,14122.61,2020-12-02 00:00:00,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466,7964
1,France,64827.80,56043.63,1/20/2019,Appliances,Gislason-Stanton,Othello Bowes,Maighdiln Upcraft,PC,62-3312495,4974
2,Portugal,71620.08,62245.01,2019-05-02 00:00:00,Books,Schoen-Keeling,Celine Tumasian,Smitty Culverhouse,NaN,69-6259390,2809
3,Portugal,74532.02,59752.32,2020-02-04 00:00:00,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183,4260
4,Portugal,78461.13,63537.82,2020-10-05 00:00:00,Appliances,Hessel-Stiedemann,Celine Tumasian,Smitty Culverhouse,Mobile,91-4126746,6038

In [27]:
final_df = pd.concat([merged_df, extra_data], ignore_index=True)
final_df

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id,refund
0,Sweden,98320.37,77722.25,2020-08-23 00:00:00,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466,43621
1,France,46296.26,40319.41,2020-05-15 00:00:00,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084,13385
2,Portugal,140337.34,115708.14,2020-04-09 00:00:00,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141,69535
3,France,203604.46,175344.16,2019-06-26 00:00:00,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106,90064
4,UK,63979.04,56032.84,2019-10-22 00:00:00,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546,24176
...,...,...,...,...,...,...,...,...,...,...,...
1004,Spain,84900.24,73701.90,7/14/2020,Clothing,"Farrell, Swaniawski and Crist",Emalia Dinse,Perri Aldersley,PC,60-6998932,7598
1005,Finland,116563.40,92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323,2928
1006,UK,156585.22,126599.15,8/30/2020,Accessories,"Hermiston, Simonis and Wisoky",Jessamine Apark,Winny Agnolo,PC,64-5761908,9376
1007,Spain,178763.42,146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160,5153
1008,Portugal,296685.56,257480.34,2019-11-07 00:00:00,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341,3955

# QUIZ 3: Solutions

# Feature engineering

In [28]:
final_df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id,refund
0,Sweden,98320.37,77722.25,2020-08-23 00:00:00,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466,43621
1,France,46296.26,40319.41,2020-05-15 00:00:00,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084,13385
2,Portugal,140337.34,115708.14,2020-04-09 00:00:00,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141,69535
3,France,203604.46,175344.16,2019-06-26 00:00:00,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106,90064
4,UK,63979.04,56032.84,2019-10-22 00:00:00,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546,24176

In [29]:
# Create a pivot table to calculate median sales and cost, and purchase frequency
pivot_table = final_df.pivot_table(index='customer_name',
                             values=['order_value_EUR', 'cost'],
                             aggfunc={'order_value_EUR': 'median', 'cost': 'median', 'customer_name': 'count'})

# Rename columns for clarity
pivot_table.columns = ['Median Cost', 'Purchase Frequency', 'Median Sales']

In [30]:
sorted_pivot_table = pivot_table.sort_values(by = 'Purchase Frequency', ascending = False)
top_10 = sorted_pivot_table[0:10]
top_10

,Median Cost,Purchase Frequency,Median Sales
customer_name,,,
Johns and Sons,86694.33,143,106115.850
Hessel-Stiedemann,79127.71,57,95960.770
"Swaniawski, Runolfsson and Green",84690.35,25,100094.970
"Dickinson, Hyatt and Berge",85886.10,24,104540.680
"Murray, Reichel and Nolan",71501.10,23,88832.280
"Rowe, Hermiston and Kessler",66065.68,22,77690.890
Larkin-Collier,105025.33,22,129035.985
Kihn Inc,66742.15,22,80450.080
Wisoky Inc,94336.18,21,115226.800
Tillman and Sons,75839.40,21,91350.760

In [31]:
top_10.index

Index(['Johns and Sons', 'Hessel-Stiedemann',
       'Swaniawski, Runolfsson and Green', 'Dickinson, Hyatt and Berge',
       'Murray, Reichel and Nolan', 'Rowe, Hermiston and Kessler',
       'Larkin-Collier', 'Kihn Inc', 'Wisoky Inc', 'Tillman and Sons'],
      dtype='object', name='customer_name')

In [32]:
# List of loyal customer names
loyal_customer_names = ['Johns and Sons', 'Hessel-Stiedemann', 'Swaniawski, Runolfsson and Green',
                        'Dickinson, Hyatt and Berge', 'Murray, Reichel and Nolan',
                        'Rowe, Hermiston and Kessler', 'Kihn Inc', 'Tillman and Sons',
                        'Wisoky Inc', 'Larkin-Collier']

# Function to assign "Loyal customer" or "Regular customer"
def customer_type(name):
    if name in loyal_customer_names:
        return "Loyal customer"
    else:
        return "Regular customer"

# Apply the function to create a new variable 'CustomerType'
final_df['CustomerType'] = final_df['customer_name'].apply(customer_type)

In [33]:
final_df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id,refund,CustomerType
0,Sweden,98320.37,77722.25,2020-08-23 00:00:00,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466,43621,Regular customer
1,France,46296.26,40319.41,2020-05-15 00:00:00,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084,13385,Loyal customer
2,Portugal,140337.34,115708.14,2020-04-09 00:00:00,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141,69535,Regular customer
3,France,203604.46,175344.16,2019-06-26 00:00:00,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106,90064,Regular customer
4,UK,63979.04,56032.84,2019-10-22 00:00:00,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546,24176,Regular customer

In [34]:
final_df['CustomerType'].value_counts()

Regular customer    629
Loyal customer      380
Name: CustomerType, dtype: int64

In [35]:
# Convert the 'Date' column to a datetime type
final_df['date'] = pd.to_datetime(final_df['date'])

# Extract day, month, and year into new columns
final_df['Day'] = final_df['date'].dt.day
final_df['Month'] = final_df['date'].dt.month
final_df['Year'] = final_df['date'].dt.year

In [36]:
final_df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id,refund,CustomerType,Day,Month,Year
0,Sweden,98320.37,77722.25,2020-08-23,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466,43621,Regular customer,23,8,2020
1,France,46296.26,40319.41,2020-05-15,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084,13385,Loyal customer,15,5,2020
2,Portugal,140337.34,115708.14,2020-04-09,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141,69535,Regular customer,9,4,2020
3,France,203604.46,175344.16,2019-06-26,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106,90064,Regular customer,26,6,2019
4,UK,63979.04,56032.84,2019-10-22,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546,24176,Regular customer,22,10,2019

In [37]:
final_df['Year'].value_counts()

2020    515
2019    494
Name: Year, dtype: int64

# Extracting Day, Month, Year

In [38]:
# Convert the 'Date' column to a datetime type
final_df['date'] = pd.to_datetime(final_df['date'])

# Extract day, month, and year into new columns
final_df['Day'] = final_df['date'].dt.day
final_df['Month'] = final_df['date'].dt.month
final_df['Year'] = final_df['date'].dt.year

In [39]:
final_df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id,refund,CustomerType,Day,Month,Year
0,Sweden,98320.37,77722.25,2020-08-23,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466,43621,Regular customer,23,8,2020
1,France,46296.26,40319.41,2020-05-15,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084,13385,Loyal customer,15,5,2020
2,Portugal,140337.34,115708.14,2020-04-09,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141,69535,Regular customer,9,4,2020
3,France,203604.46,175344.16,2019-06-26,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106,90064,Regular customer,26,6,2019
4,UK,63979.04,56032.84,2019-10-22,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546,24176,Regular customer,22,10,2019

In [40]:
final_df['Year'].value_counts()

2020    515
2019    494
Name: Year, dtype: int64

# Feature Encoding

In [41]:
# Replace values in the 'CustomerType' column
final_df['CustomerType_encoded'] = final_df['CustomerType'].replace({'Loyal customer': 1, 'Regular customer': 0})

In [42]:
final_df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id,refund,CustomerType,Day,Month,Year,CustomerType_encoded
0,Sweden,98320.37,77722.25,2020-08-23,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466,43621,Regular customer,23,8,2020,0
1,France,46296.26,40319.41,2020-05-15,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084,13385,Loyal customer,15,5,2020,1
2,Portugal,140337.34,115708.14,2020-04-09,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141,69535,Regular customer,9,4,2020,0
3,France,203604.46,175344.16,2019-06-26,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106,90064,Regular customer,26,6,2019,0
4,UK,63979.04,56032.84,2019-10-22,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546,24176,Regular customer,22,10,2019,0

# Creating Dummy variable

In [43]:
# Create dummy variables for categorical columns
prep_df = pd.get_dummies(final_df, columns=['country', 'category', 'device_type'])

In [44]:
prep_df.head()

,order_value_EUR,cost,date,customer_name,sales_manager,sales_rep,order_id,refund,CustomerType,Day,...,category_Books,category_Clothing,category_Electronics,category_Games,category_Other,category_Outdoors,category_Smartphones,device_type_Mobile,device_type_PC,device_type_Tablet
0,98320.37,77722.25,2020-08-23,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,70-0511466,43621,Regular customer,23,...,0,0,0,1,0,0,0,0,0,1
1,46296.26,40319.41,2020-05-15,Wisoky Inc,Othello Bowes,Amelina Piscopiello,77-3489084,13385,Loyal customer,15,...,0,0,0,1,0,0,0,0,0,1
2,140337.34,115708.14,2020-04-09,Hegmann Group,Celine Tumasian,Corene Shirer,65-8218141,69535,Regular customer,9,...,0,0,0,0,0,0,0,0,1,0
3,203604.46,175344.16,2019-06-26,Kirlin and Sons,Othello Bowes,Crysta Halls,29-5478106,90064,Regular customer,26,...,0,0,1,0,0,0,0,1,0,0
4,63979.04,56032.84,2019-10-22,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,27-3437546,24176,Regular customer,22,...,0,0,0,1,0,0,0,0,1,0

# Feature Scaling

In [45]:
y = prep_df['refund']

In [46]:
prep_df.columns

Index(['order_value_EUR', 'cost', 'date', 'customer_name', 'sales_manager',
       'sales_rep', 'order_id', 'refund', 'CustomerType', 'Day', 'Month',
       'Year', 'CustomerType_encoded', 'country_Austria', 'country_Belgium',
       'country_Bulgaria', 'country_Denmark', 'country_Finland',
       'country_France', 'country_Germany', 'country_Ireland', 'country_Italy',
       'country_Luxembourg', 'country_Netherlands', 'country_Portugal',
       'country_Spain', 'country_Sweden', 'country_UK', 'category_Accessories',
       'category_Appliances', 'category_Beauty', 'category_Books',
       'category_Clothing', 'category_Electronics', 'category_Games',
       'category_Other', 'category_Outdoors', 'category_Smartphones',
       'device_type_Mobile', 'device_type_PC', 'device_type_Tablet'],
      dtype='object')

In [47]:
# List of categorical variables to drop
variables_to_drop = ['date', 'customer_name', 'sales_manager', 'sales_rep', 'order_id', 'refund', 'CustomerType']

# Drop the specified columns
x = prep_df.drop(variables_to_drop, axis=1)

In [48]:
x.columns

Index(['order_value_EUR', 'cost', 'Day', 'Month', 'Year',
       'CustomerType_encoded', 'country_Austria', 'country_Belgium',
       'country_Bulgaria', 'country_Denmark', 'country_Finland',
       'country_France', 'country_Germany', 'country_Ireland', 'country_Italy',
       'country_Luxembourg', 'country_Netherlands', 'country_Portugal',
       'country_Spain', 'country_Sweden', 'country_UK', 'category_Accessories',
       'category_Appliances', 'category_Beauty', 'category_Books',
       'category_Clothing', 'category_Electronics', 'category_Games',
       'category_Other', 'category_Outdoors', 'category_Smartphones',
       'device_type_Mobile', 'device_type_PC', 'device_type_Tablet'],
      dtype='object')

In [49]:
from sklearn.preprocessing import StandardScaler

In [50]:
# Initialize the StandardScaler
scaler = StandardScaler()

# Scale the numeric columns
scaled_data = scaler.fit_transform(x)

In [51]:
scaled_data

array([[-0.24271229, -0.32322742,  0.83856758, ..., -0.40966337,
        -1.89376969,  3.55459353],
       [-1.08746076, -1.0471347 , -0.07282565, ..., -0.40966337,
        -1.89376969,  3.55459353],
       [ 0.43954391,  0.41196441, -0.75637057, ..., -0.40966337,
         0.52804732, -0.28132612],
       ...,
       [ 0.70337104,  0.62275272,  1.63603666, ..., -0.40966337,
         0.52804732, -0.28132612],
       [ 1.06349254,  1.01027712,  0.72464343, ..., -0.40966337,
        -1.89376969,  3.55459353],
       [ 2.97826913,  3.15587176, -0.98421888, ..., -0.40966337,
         0.52804732, -0.28132612]])

# Splitting Data

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
# Split the data into training and testing sets
train_x, test_x, train_y, test_y = train_test_split(scaled_data, y, test_size=0.25, random_state=42)